name: '2. Develop'

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  default:
    name: Default
    uses: renanphellip/api-management-nested-workflows/.github/workflows/develop.yml@main
