name: '3. Gates'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - 'release/v*'

jobs:
  gates:
    name: Gates
    uses: renanphellip/api-management-nested-workflows/.github/workflows/core-gates.yml@main
