name: '3. Gates'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - 'release/v*'

jobs:
  default:
    name: Default
    uses: renanphellip/api-management-nested-workflows/.github/workflows/gates.yml@main
