name: '5. Main'

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  main:
    name: Main
    uses: renanphellip/api-management-nested-workflows/.github/workflows/main.yml@main
