name: '5. Main'

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  default:
    name: Default
    uses: renanphellip/api-management-nested-workflows/.github/workflows/main.yml@main
