name: '4. Release'

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/v*'

jobs:
  default:
    name: Default
    uses: renanphellip/api-management-nested-workflows/.github/workflows/release.yml@main
