name: '4. Release'

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/v*'

jobs:
  release:
    name: Release
    uses: renanphellip/api-management-nested-workflows/.github/workflows/core-release.yml@main
